title: 开发文档
description: Fourier-GRX SDK
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

logo: "assets/images/logo.png"
logo_alt: "Fourier Intelligence"

search_enabled: true
collapse_navigation: true
navigation_fixed: true
navigation_sticky: true
navigation_fold: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# 可选扩展配置
aux_links:
  "GitHub 仓库":
    - "//github.com/FFTAI/Wiki-GRx-Deploy"